name: 'TypeScript Error Reporter'
description: 'Report type check result on PR diff view.'
author: 'andoshin11'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  project:
    description: 'Optional project path.'
    required: false
